version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpwd
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpwd
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpwd@mongo:27017
    depends_on:
      - mongo

  minesweeper-api:
    image: minesweeper-api:latest
    ports:
      - 8088:8088
    depends_on:
      - mongo